# Spring HTTP Port
server.port=8081

# ── Global GOSI Kafka Connection Properties ──
gosi.kafka.bootstrap-servers=rb.apps.appsqaocp.gosi.ins:443
gosi.kafka.security-protocol=SASL_SSL
gosi.kafka.sasl-mechanism=OAUTHBEARER
gosi.kafka.oauth-token-url=https://identitydev.gosi.gov.sa/am/oauth2/realms/root/realms/wiam/access_token
gosi.kafka.username=confluent
gosi.kafka.password=GOSIwiam@2025

# Schema Registry Bearer Auth
gosi.kafka.properties.bearer.auth.credentials.source=OAUTHBEARER
gosi.kafka.properties.bearer.auth.issuer.endpoint.url=https://identitydev.gosi.gov.sa/am/oauth2/realms/root/realms/wiam/access_token
gosi.kafka.properties.bearer.auth.client.id=confluent
gosi.kafka.properties.bearer.auth.client.secret=GOSIwiam@2025
gosi.kafka.properties.bearer.auth.scope=write

# TLS Configuration
gosi.kafka.truststore-location=truststore.jks
gosi.kafka.truststore-password=mystorepassword

app.kafka.topic=<your-namespace>.<your-topic-name>.<v(n)>

# Schema Registry
gosi.kafka.schema-registry-url=https://schema-registry.apps.appsqaocp.gosi.ins

gosi.kafka.group-id=<your-consumer-group-id>

# Console Log Pattern with Trace ID
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} [TraceID: %X{trace_id}] - %msg%n
